FROM docker.io/library/eclipse-temurin:21-jre
WORKDIR /app
# Must match bootJar.archiveFileName in build.gradle
COPY build/libs/{{FUNCTION_NAME}}.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
