org.gradle.jvmargs=-Xmx1g
springBootVersion=4.1.1
springDependencyManagementVersion=1.1.7
graalvmBuildToolsVersion=1.1.14
graalvmVersion=25.2.4
graalvmJavaVersion=25.0.4
sonarQubePluginVersion=7.5.0.8588
spotbugsGradlePluginVersion=6.5.11
spotbugsVersion=4.10.4
errorProneGradlePluginVersion=5.1.1
errorProneVersion=2.50.0
pmdVersion=7.28.0
javaVersion=25
