org.gradle.jvmargs=-Xmx1g
springBootVersion=4.1.0
springDependencyManagementVersion=1.1.7
graalvmBuildToolsVersion=1.1.6
graalvmVersion=25.2.4
graalvmJavaVersion=25.0.4
sonarQubePluginVersion=7.3.1.8318
spotbugsGradlePluginVersion=6.5.11
spotbugsVersion=4.10.4
errorProneGradlePluginVersion=5.1.1
errorProneVersion=2.50.0
javaVersion=25
