plugins {
    id 'application'
    id 'org.graalvm.buildtools.native' version "${graalvmBuildToolsVersion}"
}

dependencies {
    implementation project(':sdks:java-lite')
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'it.unimib.datai.nanofaas.examples.romannumerallite.RomanNumeralLite'
}

graalvmNative {
    binaries {
        main {
            imageName = 'roman-numeral-lite'
            mainClass = 'it.unimib.datai.nanofaas.examples.romannumerallite.RomanNumeralLite'
        }
    }
}
