plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
    }
}

dependencies {
    api project(':container-deployment-runtime')
    implementation project(':common')
    implementation project(':control-plane-spi')
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'io.github.nanofaas:containerd-java-cni:0.25.0'
    implementation 'com.google.protobuf:protobuf-java:4.36.2'
    runtimeOnly 'com.google.protobuf:protobuf-java-util:4.36.2'

    testImplementation project(':control-plane')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.5.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
