package it.unimib.datai.nanofaas.modules.buildmetadata;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies the {@code META-INF/nanofaas-build.properties} resource generated by the
 * {@code generateBuildMetadata} Gradle task satisfies what {@link BuildMetadataProvider} expects.
 */
class GeneratedBuildMetadataTest {

    @Test
    void generatedPropertiesSatisfyProvider() throws IOException {
        Properties properties = new Properties();
        try (InputStream in = getClass().getClassLoader()
                .getResourceAsStream("META-INF/nanofaas-build.properties")) {
            assertThat(in).as("META-INF/nanofaas-build.properties on the classpath").isNotNull();
            properties.load(in);
        }

        assertThat(properties.getProperty("version"))
                .isEqualTo(System.getProperty("project.version"));
        // A git-less build (source tarball, container build without .git) legitimately
        // omits revision; when present, it must be a real commit SHA.
        assertThat(properties.getProperty("revision")).satisfiesAnyOf(
                revision -> assertThat(revision).isNull(),
                revision -> assertThat(revision).matches("[0-9a-f]{40}"));
        assertThat(properties.getProperty("dirty")).isIn("true", "false");
        assertThat(properties.getProperty("modules").split(","))
                .contains("build-metadata").isSorted();
        // Matches whatever build type was actually requested (e.g. -PnanofaasBuildType=native),
        // 'jvm' by default.
        assertThat(properties.getProperty("type")).isEqualTo(System.getProperty("nanofaasBuildType"));
    }
}
